-- =====================================================
-- 1. ENUMS
-- =====================================================
CREATE TYPE tshirt_size_enum AS ENUM ('S', 'M', 'L', 'XL');
CREATE TYPE order_status AS ENUM ('pending', 'processing', 'shipped', 'delivered');
CREATE TYPE message_mode_type AS ENUM ('anonymous', 'non_anonymous', 'friends_only');

-- FIX #9: was VARCHAR(20), now a proper enum
CREATE TYPE friend_status_enum AS ENUM ('pending', 'accepted', 'rejected');


-- =====================================================
-- 2. USERS
-- =====================================================
CREATE TABLE users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id  BIGINT NOT NULL,
    mobile      VARCHAR(15)        NOT NULL UNIQUE,
    email       VARCHAR(255)       NOT NULL UNIQUE,
    name        VARCHAR(255)       NOT NULL,

    -- FIX #4: added visibility mode column
    visibility  message_mode_type  NOT NULL DEFAULT 'non_anonymous',

    profile_pic TEXT,
    know_me     TEXT,

    -- FIX #16: nullable — QR is generated after registration
    qr_code     TEXT,

    -- FIX #5 & #6: removed vote_count (derived from votes table) and
    --              removed class_img (belongs on users for submission only,
    --              but kept here since it's the user's submitted photo)
    class_img   TEXT,

    -- FIX #7: removed t_shirt_size — size is captured at order time only,
    --         storing it here creates a split-brain between users and main_t_shirts
    --         If you want a preference, rename it clearly:
    t_shirt_size_preference tshirt_size_enum,

    -- FIX #17: soft delete instead of hard delete
    deleted_at  TIMESTAMPTZ,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 3. COLLEGES / BRANCHES / SECTIONS
-- =====================================================
CREATE TABLE colleges (
    college_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_name VARCHAR(255) NOT NULL,
    address      TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP
);

-- FIX #15: wired organization into the hierarchy above colleges
--          instead of leaving it as a disconnected duplicate
CREATE TABLE organizations (
    organization_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(255) NOT NULL,
    address           TEXT         NOT NULL,
    created_at        TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE branches (
    branch_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id  BIGINT NOT NULL,
    branch_name TEXT   NOT NULL,
    CONSTRAINT fk_branches_college
        FOREIGN KEY (college_id) REFERENCES colleges(college_id) ON DELETE CASCADE,
    CONSTRAINT unique_branch_per_college UNIQUE (college_id, branch_name)
);
CREATE INDEX idx_branches_college_id ON branches(college_id);

CREATE TABLE sections (
    section_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       BIGINT       NOT NULL,
    section_name    VARCHAR(255) NOT NULL, --seciton_name
    class_pic_final TEXT,
    strength INT NOT NULL,
    CONSTRAINT fk_sections_branch
        FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE CASCADE,
    CONSTRAINT unique_section_per_branch UNIQUE (branch_id, section_name)
);
CREATE INDEX idx_sections_branch_id ON sections(branch_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_section
        FOREIGN KEY (section_id) REFERENCES sections(section_id) ON DELETE RESTRICT;


-- =====================================================
-- 4. VOTES  (FIX #1 + #5)
-- replaces vote_count column on users
-- =====================================================
CREATE TABLE votes (
    vote_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_id    BIGINT      NOT NULL,
    voted_for   BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_votes_voter
        FOREIGN KEY (voter_id)  REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_votes_voted_for
        FOREIGN KEY (voted_for) REFERENCES users(user_id) ON DELETE CASCADE,
    -- enforces ALREADY_VOTED and CANNOT_VOTE_SELF at DB level
    CONSTRAINT unique_vote_per_voter UNIQUE (voter_id),
-- might not have this    CONSTRAINT no_self_vote CHECK (voter_id <> voted_for)
);
CREATE INDEX idx_votes_voted_for ON votes(voted_for);
-- vote count is now: SELECT COUNT(*) FROM votes WHERE voted_for = $1
-- or use a view:
CREATE VIEW user_vote_counts AS
    SELECT voted_for AS user_id, COUNT(*) AS vote_count
    FROM votes
    GROUP BY voted_for;


-- =====================================================
-- 5. FOLLOWERS
-- =====================================================
CREATE TABLE followers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    followee   BIGINT             NOT NULL,
    follower   BIGINT             NOT NULL,

    -- FIX #9: was VARCHAR(20)
    status     friend_status_enum NOT NULL DEFAULT 'pending',

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- FIX #14: know when a request was accepted or rejected
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CHECK (followee <> follower),
    CONSTRAINT unique_follow_pair UNIQUE (
        LEAST(followee, follower),
        GREATEST(followee, follower)
    ),
    CONSTRAINT fk_followers_followee
        FOREIGN KEY (followee) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_followers_follower
        FOREIGN KEY (follower) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_followers_follower        ON followers(follower);
CREATE INDEX idx_followers_followee        ON followers(followee);
CREATE INDEX idx_followers_follower_status ON followers(follower, status);
CREATE INDEX idx_followers_followee_status ON followers(followee, status);


-- =====================================================
-- 6. PAYMENTS  (FIX #11)
-- =====================================================
CREATE TABLE payments (
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT         NOT NULL,
    amount         NUMERIC(10, 2) NOT NULL,
    status         VARCHAR(50)    NOT NULL DEFAULT 'pending',
    provider_ref   TEXT,          -- external payment gateway reference
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT
);
CREATE INDEX idx_payments_user_id ON payments(user_id);


-- =====================================================
-- 7. T-SHIRT ORDERS
-- =====================================================
CREATE TABLE main_t_shirts (
    main_t_shirt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT           NOT NULL,
    payment_id      BIGINT,          -- FIX #11: link to payment

    -- FIX #6 & #7: removed class_img — derive it from sections.class_pic_final
    --              via the user's section_id at query time. No duplication.
    --              size is stored here at order time (not on users).
    size            tshirt_size_enum NOT NULL,
    status          order_status     NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_main_tshirts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_main_tshirts_payment
        FOREIGN KEY (payment_id) REFERENCES payments(payment_id) ON DELETE SET NULL,
    CONSTRAINT main_tshirt_unique_user UNIQUE (user_id)
);
CREATE INDEX idx_main_tshirts_status ON main_t_shirts(status);

CREATE TABLE personal_shirts (
    personal_t_shirt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    payment_id          BIGINT,      -- FIX #11
    -- FIX #10: NOT NULL to match main_t_shirts
    status              order_status NOT NULL DEFAULT 'pending',
    nft                 TEXT,
    grafic_img          TEXT,
    created_at          TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_personal_shirts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_personal_shirts_payment
        FOREIGN KEY (payment_id) REFERENCES payments(payment_id) ON DELETE SET NULL,
    CONSTRAINT personal_shirts_unique_user UNIQUE (user_id)
);
CREATE INDEX idx_personal_shirts_status ON personal_shirts(status);


-- =====================================================
-- 8. SLAM BOOKS
-- =====================================================
CREATE TABLE slam_books (
    slam_book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT       NOT NULL,
    payment_id   BIGINT,      -- FIX #11
    -- FIX #3: nullable — PDF is generated after the order is placed
    pdf_url      TEXT,
    status       order_status NOT NULL DEFAULT 'pending',
    -- FIX #13: added missing created_at
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_slam_books_owner
        FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_slam_books_payment
        FOREIGN KEY (payment_id) REFERENCES payments(payment_id) ON DELETE SET NULL,
    CONSTRAINT slam_books_owner_unique UNIQUE (owner_id)
);
CREATE INDEX idx_slam_books_status ON slam_books(status);


-- =====================================================
-- 9. SIGNATURES
-- =====================================================
CREATE TABLE signatures (
    sign_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT             NOT NULL,
    sticker      TEXT,
    quote        VARCHAR(255)       NOT NULL,
    author       BIGINT,
    message      TEXT,
    type         message_mode_type  NOT NULL DEFAULT 'anonymous',

    -- FIX #12: dropped in_book boolean — derive it as (slam_book_id IS NOT NULL)
    --          keeping both created an enforceability problem; one source of truth is cleaner

    media_file   TEXT,
    -- slam_book_id BIGINT,
    in_book      BOOLEAN            DEFAULT FALSE NOT NULL,
    signed_at    TIMESTAMPTZ        DEFAULT CURRENT_TIMESTAMP,
    viewed       BOOLEAN            NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_signatures_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_signatures_author
        FOREIGN KEY (author) REFERENCES users(user_id) ON DELETE SET NULL,
    --  SET NULL so the sign survives if the sender deletes their account (anonymous anyway)
    -- CONSTRAINT fk_signatures_slam_book
    --     FOREIGN KEY (slam_book_id) REFERENCES slam_books(slam_book_id) ON DELETE SET NULL,

    -- FIX #8 (partial): non-anonymous uniqueness — one named sign per sender per recipient
    CONSTRAINT unique_named_signature_per_author UNIQUE (user_id, author)
    -- author = NULL case is handled by the partial index below
);

-- FIX #2: separate partial index for anonymous signs — one per recipient
CREATE UNIQUE INDEX unique_anon_sign_per_user
    ON signatures(user_id)
    WHERE author IS NULL;

CREATE INDEX idx_signatures_user_id          ON signatures(user_id);
CREATE INDEX idx_signatures_user_id_type     ON signatures(user_id, type);
-- FIX #12: replaced (user_id, in_book) with (user_id, slam_book_id)
CREATE INDEX idx_signatures_user_slam_book   ON signatures(user_id, in_book);
CREATE INDEX idx_signatures_author           ON signatures(author);
-- CREATE INDEX idx_signatures_in_book          ON signatures(in_book);
CREATE INDEX idx_signatures_signed_at        ON signatures(signed_at DESC);
